spring.config.import:
  - classpath:domain-employees-config.yml
  - classpath:domain-projects-config.yml
  - classpath:domain-skills-config.yml

---

server:
  shutdown: graceful

custom:
  security:
    cors:
      allowed-origins: "http://localhost:4200"
