graphql:
  servlet:
    actuator-metrics: true
    mapping: /api/graphql
    exception-handlers-enabled: false

logging:
  level:
    root: INFO
    skillmanagement: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/database"
    username: user
    password: password
  elasticsearch:
    rest:
      uris: "http://localhost:9200"
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: false
  rabbitmq:
    host: localhost
    port: 5672
